server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoDB
    username: postgres
    password: postgres
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
